## Name and notify
batch_name   = "tcflab"
notification = Error
notify_user  = hries@wisc.edu

## Resource request
request_cpus   = 0
request_memory = 100GB
request_disk   = 5GB
request_gpus   = 1
+WantGPULab    = true
+GPUJobLength  = "short"

## Universe
universe            = docker
docker_image        = rieshunter/tcflab:v2.04
docker_network_type = host

## Debugging
log    = 01-$(Cluster)_$(Process)_log
output = 02-$(Cluster)_$(Process)_output
error  = 03-$(Cluster)_$(Process)_error

## File transfer
when_to_transfer_output = ON_EXIT
should_transfer_files   = YES
environment             = state=$(state)

## Manifest
transfer_input_files    = $(state)_filtered.fastq.gz,$(state)_R1_filtered.fastq.gz,$(state)_R2_filtered.fastq.gz
arguments               = $(state)
executable              = sh_SNIFFLES-2-normalize.sh
environment             = state=$(state)

queue state from states.txt
