## Name and notify
batch_name   = "tcflab"
notification = Error
notify_user  = hries@wisc.edu

## Resource request
request_cpus   = 1
request_memory = 5GB
request_disk   = 1GB
request_gpus   = 1
+WantGPULab    = true
+GPUJobLength  = "short"

## Universe
universe            = docker
docker_image        = rieshunter/tcflab:v2.04
docker_network_type = host

## Debugging
log    = 01-$(Cluster)_$(Process)_log
output = 02-$(Cluster)_$(Process)_output
error  = 03-$(Cluster)_$(Process)_error

## File transfer
when_to_transfer_output = ON_EXIT
should_transfer_files   = YES
environment             = state=$(state)

## Manifest
transfer_input_files    = $(state)_call.vcf,/home/hries/SNIFFLES_V3/refseqs/18-19_H3N2_within-season_consensus.fasta
arguments               = $(state)
executable              = sh_SNIFFLES-4-consensus.sh
environment             = state=$(state);ref=18-19_H3N2_within-season_consensus.fasta

queue state from states.txt

## refseqs
# H3N2-A_Hong_Kong_4801_2014.fasta
# H3N2-A_Singapore_INFIMH-16-0019_2016.fasta
# H1N1-A_Michigan_45_2015.fasta

# 17-18_H1N1_within-season_consensus.fasta
# 17-18_H3N2_within-season_consensus.fasta
# 18-19_H1N1_within-season_consensus.fasta
# 18-19_H3N2_within-season_consensus.fasta

